source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'json', '~> 1.7.5'

gem 'acts-as-taggable-on', '~> 2.3.3'

# Using Capybara with RSpec:
#   http://rubydoc.info/github/jnicklas/capybara#Using_Capybara_with_RSpec
gem 'capybara', '~> 1.1.2', :groups => :test

gem 'sqlite3', :groups => [:test, :development]
group :production do
  gem 'pg'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
#  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'


  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
 
  gem 'jquery-ui-rails', '~> 2.0.2'
  gem 'jquery-datatables-rails', '~> 1.11.1'
end

gem 'jquery-rails', '~> 2.1.3'


# latwiejsze w uzyciu formularze
# zobacz https://github.com/plataformatec/simple_form
gem 'simple_form'

group :development do
  # ladniejsze wypisywanie rekordow na konsoli
  # (zob. konfiguracja irb w ~/.irbrc)
  gem 'hirb'
  # bezproblemowe zapelnianie bazy danymi testowymi
  # https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md
  # gem 'factory_girl_rails', '~> 1.2'
  # gem 'faker'
  # gem 'populator'
  # wylacza logowanie *assets pipeline*
  gem 'quiet_assets', '~> 1.0.1'
  gem 'twitter-bootstrap-rails'
  gem 'rspec-rails', '~> 2.11.0'
end
# alternatywa dla serwera Webrick
gem 'thin'
gem 'rmagick', '~> 2.13.1'
gem 'carrierwave', '~> 0.7.0'
gem 'paperclip', '~> 3.0'